routes/web.php
<?php

//User Routes
Route::group(['namespace' =>'User','middleware'=>'auth'], function(){
	Route::get('/', 'HomeController@index')->name('home');
	
	Route::get('/post/{slug}', 'PostController@post')->name('post');

	Route::get('/post/category/{category}','HomeController@category')->name('category');

	Route::get('/post/tag/{tag}','HomeController@tag')->name('tag');
});

//Admin Routes
Route::group(['namespace' =>'Admin'], function(){

	Route::get('/admin/home','HomeController@index');

	//Posts Route
	Route::resource('admin/post','PostController');

	//Tag Routes
	Route::resource('admin/tag','TagController');

	//Category Routes
	Route::resource('admin/category','CategoryController');

	//Users Routes
	Route::resource('admin/user','UserController');

	//Roles Route
	Route::resource('admin/role','RoleController');

	//Permissions Route
	Route::resource('admin/permission', 'PermissionController');

	//Admin Auth Routes
	Route::get('admin/login', 'Auth\LoginController@showLoginForm')->name('admin.login');

    Route::post('admin/login', 'Auth\LoginController@login');

    Route::post('admin/logout' ,'Auth\LoginController@logout')->name('admin.logout');
});





Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Models/User/Post.php
<?php

namespace App\Models\User;

use App\Models\User\Category;
use App\Models\User\Tag;
use Illuminate\Database\Eloquent\Model;

class Post extends Model
{   
    protected $fillable = [
    	'title','subtitle','body','image',
    	'slug','publish','like','dislike',
    	'user_id'
    ];

    //relation between Posts And Tags
    
    public function tags(){
        return $this->belongsToMany(Tag::class,'Post_tags')
        ->withTimestamps();
    }


    public function categories(){
        return $this->belongsToMany(Category::class,'category_posts')->withTimestamps();;
    }

   
}

app/Http/Controllers/Admin/PostController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\User\Category;
use App\Models\User\Post;
use App\Models\User\Tag;
use Illuminate\Http\Request;

class PostController extends Controller
{   

     /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth:admin');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {  
        $posts = Post::all();
        return view('admin.post.index',compact('posts'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {   $tags = Tag::all();
        $categories = Category::all();
        return view('admin.post.post',compact('tags','categories'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request,[
            'title'    =>'required',
            'subtitle' => 'required',
            'body'     => 'required',
            'image'     => 'required'
        ]);
       $imageName = $request->image->store('public');
       $post = new Post;
       $post->title = $request->title;
       $post->subtitle = $request->subtitle;
       $post->image = $imageName;
       $post->body = $request->body;
       $post->slug = $request->slug;
       if($request->status){
        $post->status = $request->status;
       }
       
       $post->save();
       $post->tags()->sync($request->tags);
       $post->categories()->sync($request->categories);

        return redirect(route('post.index'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {   $tags = Tag::all();

        $categories = Category::all();

        $post = Post::with('tags','categories')->findOrFail($id);
       // dd($post);

        return view('Admin.post.edit',compact('post','tags','categories'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {   

        $this->validate($request,[
            'title'    =>'required',
            'subtitle' => 'required',
            'body'     => 'required',
            
        ]);

        if($request->hasFile('image')){
            $imageName = $request->image->store('public');
            $post->image =  $imageName;
        }
        $post = Post::find($id);
        $post->title = $request->title;
        $post->subtitle = $request->subtitle;
        $post->body = $request->body;
        $post->slug = $request->slug;
        if( $request->status ){
         $post->status = $request->status;   
        }
        else{
           $post->status = 0; 
        }
        //dd($request->all());
        $post->tags()->sync($request->tags);
        $post->categories()->sync($request->categories);
        $post->save();

        return redirect(route('post.index'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {   //return $id;
        $post = Post::findOrFail($id)->delete();
        return back();
    }
}

app/Http/Controllers/User/PostController.php
<?php

namespace App\Http\Controllers\User;

use App\Http\Controllers\Controller;
use App\Models\User\Post;
use Illuminate\Http\Request;

class PostController extends Controller
{
    public function post($slug){
    	$post = Post::with('categories')->with('tags')
    	->where('slug',$slug)->first();
    	//dd($post);
    	return view('user.post',compact('post'));
    }
}

resources/views/admin/post/edit.blade.php
@extends('admin.app')
@section('style')
<link rel="stylesheet" href="{{asset('admin/bower_components/select2/dist/css/select2.min.css')}}">
@endsection
@section('main-content')
<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
  <!-- Content Header (Page header) -->
  <section class="content-header">
    <h1>
    Text Editors
    <small>Advanced form element</small>
    </h1>
    <ol class="breadcrumb">
      <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
      <li><a href="#">Forms</a></li>
      <li class="active">Editors</li>
    </ol>
  </section>
  <!-- Main content -->
  <section class="content">
    <div class="row">
      <div class="col-md-12">
        
        <!-- general form elements -->
        <div class="box box-primary">
          <div class="box-header with-border">
            <h3 class="box-title">Posts</h3>
          </div>
          @include('includes.error')
          <!-- /.box-header -->
          <!-- form start -->
          <form role="form" action="{{ route('post.update',$post->id)}}" method="post" enctype="multipart/form-data">
            {{ csrf_field() }}
            {{ method_field('PATCH') }}
            <div class="box-body">
              <div class="col-sm-6">
                <div class="form-group">
                  <label for="title">Post Title</label>
                  <input type="text" class="form-control{{$errors->has('title')?' has-error':''}}" id="title" name="title" placeholder="Title" value="{{$post->title}}">
                </div>
                <div class="form-group">
                  <label for="subtitle">Post Sub Title</label>
                  <input type="text" class="form-control{{$errors->has('subtitle')?' has-error':''}}" id="subtitle" name="subtitle" placeholder="Sub Title" value="{{$post->subtitle}}">
                </div>
                <div class="form-group">
                  <label for="subtitle">Post Slug</label>
                  <input type="text" class="form-control{{$errors->has('slug')?' has-error':''}}" id="slug" name="slug" placeholder="Slug" value="{{$post->slug}}">
                </div>
              </div>
              <div class="col-sm-6">
                <br>
                <div class="form-group">
                  <div class="pull-left">
                    <label for="image">File input</label>
                    <input type="file" id="image" name="image">
                  </div>
                  <div class="checkbox pull-right">
                    <label>
                      <input type="checkbox" name="status"
                      @if($post->status == 1) checked @endif value="1">Publish
                    </label>
                  </div>
                </div>
                <br>
                
                <div class="form-group"style="margin-top: 18px;">
                  <label>Select Tags</label>
                  <select class="form-control select2" multiple="multiple" data-placeholder="Select a Tag"
                    style="width: 100%;" name="tags[]">
                    @foreach($tags as $tag)
                    <option value="{{$tag->id}}"
                      @foreach($post->tags as $postTag)
                      @if($postTag->id == $tag->id)
                      selected
                      @endif
                      @endforeach
                    >{{$tag->name}}</option>
                    @endforeach
                  </select>
                </div>
                <!-- /.form-group -->
                <div class="form-group" style="margin-top: 18px;">
                  <label>Select Categories</label>
                  <select class="form-control select2" multiple="multiple" data-placeholder="Select a Category"
                    style="width: 100%;" name="categories[]">
                    @foreach($categories as $category)
                    <option value="{{$category->id}}"
                      @foreach($post->categories as $postCategory)
                      @if($postCategory->id == $category->id)
                      selected
                      @endif
                      @endforeach
                      >
                      {{$category->name}}
                    </option>
                    @endforeach
                    
                    
                  </select>
                </div>
                <!-- /.form-group -->
              </div>
            </div>
            <!-- /.box-body -->
            <!-- /.box -->
            <div class="box">
              <div class="box-header">
                <h3 class="box-title">Write Post body
                <small>Simple and fast</small>
                </h3>
                <!-- tools box -->
                <div class="pull-right box-tools">
                  <button type="button" class="btn btn-default btn-sm" data-widget="collapse" data-toggle="tooltip"
                  title="Collapse">
                  <i class="fa fa-minus"></i></button>
                </div>
                <!-- /. tools -->
              </div>
              <!-- /.box-header -->
              <div class="box-body pad">
                
                <textarea class="form-control{{$errors->has('body')?' has-error':''}}" placeholder="Place some text here" name="body"
                style="width: 100%; height: 500px; font-size: 14px; line-height: 18px; border: 1px solid #dddddd; padding: 10px;" id="editor1">{{$post->body}}</textarea>
                
              </div>
            </div>
            <div class="box-footer">
              <button type="submit" class="btn btn-primary">Submit</button>
              <a class="btn btn-warning" href="{{route('post.index')}}">Back</a>
            </div>
          </form>
        </div>
      </div>
      
      
      <!-- /.col-->
    </div>
    <!-- ./row -->
  </section>
  <!-- /.content -->
</div>
<!-- /.content-wrapper -->
@endsection
@section('script')
<!-- Select2 -->
<script src="{{asset('admin/bower_components/select2/dist/js/select2.full.min.js')}}">
</script>
<!-- CK Editor -->
<script src="{{asset('admin/bower_components/ckeditor/ckeditor.js')}}">
</script>
<script>
$(function () {
// Replace the <textarea id="editor1"> with a CKEditor
// instance, using default configuration.
CKEDITOR.replace('editor1')
//bootstrap WYSIHTML5 - text editor
$('.textarea').wysihtml5()
})
</script>
<script>
$('document').ready(function(){
//Initialize Select2 Elements
$('.select2').select2()
});
</script>
@endsection

resources/views/admin/post/index.blade.php
@extends('admin.app')
@section('style')
<link rel="stylesheet" type="text/css" href="{{asset('admin/bower_components/datatables.net-bs/css/dataTables.bootstrap.min.css')}}">
@endsection
@section('main-content')
<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
  <!-- Content Header (Page header) -->
  <section class="content-header">
    <h1>
    Blank page
    <small>it all starts here</small>
    </h1>
    <ol class="breadcrumb">
      <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
      <li><a href="#">Examples</a></li>
      <li class="active">Blank page</li>
    </ol>
  </section>
  <!-- Main content -->
  <section class="content">
    <!-- Default box -->
    <div class="box">
      <div class="box-header with-border">
        <h3 class="box-title">Posts</h3>
        <a class="col-sm-offset-5 btn btn-success" href="{{route('post.create')}}">Add New Post</a>
        <div class="box-tools pull-right">
          <button type="button" class="btn btn-box-tool" data-widget="collapse" data-toggle="tooltip"
          title="Collapse">
          <i class="fa fa-minus"></i></button>
          <button type="button" class="btn btn-box-tool" data-widget="remove" data-toggle="tooltip" title="Remove">
          <i class="fa fa-times"></i></button>
        </div>
      </div>
      <div class="box-body">
        <div class="box">
          <div class="box-header">
            <h3 class="box-title">Data Table With Full Features</h3>
          </div>
          <!-- /.box-header -->
          <div class="box-body">
            <table id="example1" class="table table-bordered table-striped">
              <thead>
                <tr>
                  <th>S.No</th>
                  <th>Post Title</th>
                  <th>Post Subtitle</th>
                  <th>Post Slug</th>
                  <th>Created-at</th>
                  <th>Status</th>
                  <th>Edit</th>
                  <th>Delete</th>
                </tr>
              </thead>
              <tbody>
                @foreach($posts as $post)
                <tr>
                  <td>{{$loop->index+1}}</td>
                  <td>{{$post->title}}</td>
                  <td>{{$post->subtitle}}</td>
                  <td>{{$post->slug}}</td>
                  <td>{{  date("d M Y", strtotime($post->created_at)) }}</td>
                  <td>
                    @if($post->status ==1)
                    Published
                    @else
                    Not Published
                  @endif</td>
                  <td><a href="{{route('post.edit',$post->id)}}"><span class="glyphicon glyphicon-edit"></span></a></td>
                  <form id='delete-form-{{$post->id}}' method="post" action="{{route('post.destroy',$post->id)}}" style="display: none;">
                    {{ csrf_field() }}
                    {{ method_field('DELETE') }}
                  </form>
                  <td><a href="#"
                    onclick="if(confirm('Are You sure, You want to delete this')){
                    event.preventDefault;
                    document.getElementById('delete-form-{{$post->id}}').submit();
                    }else{
                    event.preventDefault;
                    }">
                    <span class="glyphicon glyphicon-trash"></span></a></td>
                  </tr>
                  @endforeach
                  
                  
                </tbody>
                <tfoot>
                <tr>
                  <th>S.No</th>
                  <th>Post Title</th>
                  <th>Post Subtitle</th>
                  <th>Post Slug</th>
                  <th>Created-at</th>
                  <th>Edit</th>
                  <th>Delete</th>
                </tr>
                </tfoot>
              </table>
            </div>
            <!-- /.box-body -->
          </div>
          <!-- /.box -->
        </div>
        <!-- /.box-body -->
        <div class="box-footer">
          Footer
        </div>
        <!-- /.box-footer-->
      </div>
      <!-- /.box -->
    </section>
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->
  @endsection
  @section('script')
  <script src="{{asset('admin/bower_components/datatables.net/js/jquery.dataTables.min.js')}}"></script>
  <script src="{{asset('admin/bower_components/datatables.net-bs/js/dataTables.bootstrap.min.js')}}"></script>
  <script>
  $(function () {
  $('#example1').DataTable()
  $('#example2').DataTable({
  'paging'      : true,
  'lengthChange': false,
  'searching'   : false,
  'ordering'    : true,
  'info'        : true,
  'autoWidth'   : false
  })
  })
  </script>
  @endsection

resources/views/admin/post/post.blade.php
@extends('admin.app')
@section('style')
<link rel="stylesheet" href="{{asset('admin/bower_components/select2/dist/css/select2.min.css')}}">
@endsection
@section('main-content')
<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
  <!-- Content Header (Page header) -->
  <section class="content-header">
    <h1>
    Text Editors
    <small>Advanced form element</small>
    </h1>
    <ol class="breadcrumb">
      <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
      <li><a href="#">Forms</a></li>
      <li class="active">Editors</li>
    </ol>
  </section>
  <!-- Main content -->
  <section class="content">
    <div class="row">
      <div class="col-md-12">
        
        <!-- general form elements -->
        <div class="box box-primary">
          <div class="box-header with-border">
            <h3 class="box-title">Posts</h3>
          </div>
          @include('includes.error')
          <!-- /.box-header -->
          <!-- form start -->
          <form role="form" action="{{ route('post.store')}}" method="post" enctype="multipart/form-data">
            {{ csrf_field() }}
            <div class="box-body">
              <div class="col-sm-6">
                <div class="form-group">
                  <label for="title">Post Title</label>
                  <input type="text" class="form-control{{$errors->has('title')?' has-error':''}}" id="title" name="title" placeholder="Title" value="{{old('title')}}">
                </div>
                <div class="form-group">
                  <label for="subtitle">Post Sub Title</label>
                  <input type="text" class="form-control{{$errors->has('subtitle')?' has-error':''}}" id="subtitle" name="subtitle" placeholder="Sub Title" value="{{old('subtitle')}}">
                </div>
                <div class="form-group">
                  <label for="subtitle">Post Slug</label>
                  <input type="text" class="form-control{{$errors->has('slug')?' has-error':''}}" id="slug" name="slug" placeholder="Slug" value="{{old('slug')}}">
                </div>
              </div>
              <div class="col-md-6">
                <div class="form-group">
                  <div class="pull-left">
                    <label for="image">File input</label>
                    <input type="file" id="image" name="image">
                  </div>
                  <div class="checkbox pull-right">
                    <label>
                      <input type="checkbox" name="status" value="1">Publish
                    </label>
                  </div>
                </div>
                <br><br>
                
                <div class="form-group"style="margin-top:20px;">
                  <label>Select Tags</label>
                  <select class="form-control select2" multiple="multiple" data-placeholder="Select a Tag"
                    style="width: 100%;" name="tags[]">
                    @foreach($tags as $tag)
                    <option value="{{$tag->id}}">{{$tag->name}}</option>
                    @endforeach
                    
                  </select>
                </div>
                <!-- /.form-group -->
                <div class="form-group" style="margin-top:20px;">
                  <label>Select Categories</label>
                  <select class="form-control select2" multiple="multiple" data-placeholder="Select a Category"
                    style="width: 100%;" name="categories[]">
                    @foreach($categories as $category)
                    <option value="{{$category->id}}">{{$category->name}}</option>
                    @endforeach
                    
                    
                  </select>
                </div>
                <!-- /.form-group -->
                
              </div>
            </div>
            <!-- /.box-body -->
            <!-- /.box -->
            <div class="box">
              <div class="box-header">
                <h3 class="box-title">Write Post body
                <small>Simple and fast</small>
                </h3>
                <!-- tools box -->
                <div class="pull-right box-tools">
                  <button type="button" class="btn btn-default btn-sm" data-widget="collapse" data-toggle="tooltip"
                  title="Collapse">
                  <i class="fa fa-minus"></i></button>
                </div>
                <!-- /. tools -->
              </div>
              <!-- /.box-header -->
              <div class="box-body pad">
                
                <textarea class="form-control{{$errors->has('body')?' has-error':''}}"name="body"
                style="width: 100%; height: 500px; font-size: 14px; line-height: 18px; border: 1px solid #dddddd; padding: 10px;" id="editor1">{{old('body')}}</textarea>
                
              </div>
            </div>
            <div class="box-footer">
              <button type="submit" class="btn btn-primary">Submit</button>
              <a class="btn btn-warning" href="{{route('post.index')}}">Back</a>
            </div>
          </form>
        </div>
      </div>
      
      
      <!-- /.col-->
    </div>
    <!-- ./row -->
  </section>
  <!-- /.content -->
</div>
<!-- /.content-wrapper -->
@endsection
@section('script')
<!-- Select2 -->
<script src="{{asset('admin/bower_components/select2/dist/js/select2.full.min.js')}}">
</script>
<!-- CK Editor -->
<script src="{{asset('admin/bower_components/ckeditor/ckeditor.js')}}">
</script>
<script>
$(function () {
// Replace the <textarea id="editor1"> with a CKEditor
// instance, using default configuration.
CKEDITOR.replace('editor1')
//bootstrap WYSIHTML5 - text editor
$('.textarea').wysihtml5()
})
</script>
<script>
$('document').ready(function(){
//Initialize Select2 Elements
$('.select2').select2()
});
</script>
@endsection